version: '3.8'
services:
  dev-database:
    image: postgres:15.0
    container_name: dev-database-database
    ports:
      - 5434:5432 #{port in myPC: port in container}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: NestAPI
    networks:
      - nestjs-nekwork
networks:
  nestjs-nekwork: